<?php

namespace ContainerM19wys0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8im0jZRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8im0jZR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8im0jZR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'alimentRepository' => ['privates', 'App\\Repository\\AlimentRepository', 'getAlimentRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'alimentRepository' => 'App\\Repository\\AlimentRepository',
            'em' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
