<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM19wys0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM19wys0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM19wys0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM19wys0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM19wys0\App_KernelDevDebugContainer([
    'container.build_hash' => 'M19wys0',
    'container.build_id' => 'bf5f667f',
    'container.build_time' => 1605351744,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM19wys0');
