<?php

namespace ContainerYM1d07d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TYD6RjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t_yD6Rj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t_yD6Rj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'alimentArchiveRepository' => ['privates', 'App\\Repository\\AlimentArchiveRepository', 'getAlimentArchiveRepositoryService', true],
            'alimentRepository' => ['privates', 'App\\Repository\\AlimentRepository', 'getAlimentRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'alimentArchiveRepository' => 'App\\Repository\\AlimentArchiveRepository',
            'alimentRepository' => 'App\\Repository\\AlimentRepository',
            'em' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
